### PR TITLE
adding convective v written by Damon

### PR DESCRIPTION
**Pull request by akidhruv**

### CODE REVIEW

**Comment by akidhruv** [comment]
@HUDamon96 please use this branch for future work. I had to create a new branch for your work because the previous ones were a bit messy

**Comment by akidhruv** [comment]
@HUDamon96 Here

**Comment by HUDamon96** [comment]
Okay, should go ahead and delete the Original Damon branch and both
convective branches?

**Comment by akidhruv** [comment]
Just delete the Damon branch.

**Pull request merged**
