### PR TITLE
Convection v

### PR DESCRIPTION
**Pull request by HUDamon96**
Convection_v

### CODE REVIEW

**Comment by akidhruv** [comment]
Damon,

The checks are failing on this branch. There are couple of problems here

1. You have multiple branches for convective v module.
2. You are changing multiple files instead of only one.

I would recommend following,

1. Copy the convective_v.py file somewhere outside of the main repository.
2. Delete all branches for convective v
3. Create a new branch from convective v from the develop branch.
4. Paste the convective_v.py back into the repo.
5. Push the changes and create a new pull request.

Try it and let me know if you need help. Also if you don't need the "Damon" branch and it is confusing you, go ahead and delete it as well.

**Comment by HUDamon96** [comment]
Hey Akash,
I definitely will make these changes as soon as possible.

Thanks
Damon

**Comment by akidhruv** [comment]
Damon,

I have corrected something already, please see the other pull request for updates

Akash

**Comment by HUDamon96** [comment]
Okay

**Pull request closed without merging**
